plugin:
  name: custom-data-type-gn250
  version: 1.2
  url: https://github.com/programmfabrik/easydb-custom-data-type-gn250
  displayname:
    de-DE: gn250-Verkn체pfung
    en-US: gn250-Referencing
  info:
    de-DE: Stellt Verkn체pfungen mit den geographischen Daten des Bundesamtes f체r Kartographie und Geod채sie her.
    en-US: Provides links to the geographic data of the Federal Agency for Cartography and Geodesy.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-gn250.js
    l10n: l10n/
custom_types:
  gn250:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      schema:
        - name: mapquest_api_key
          parameters:
            value:
              type: text
      mask:
        - name: show_infopopup
          parameters:
            value:
              type: bool
